import { createContext, useContext, useState, useEffect, ReactNode } from "react";

type Language = "en" | "ar";

interface LanguageContextType {
  language: Language;
  toggleLanguage: () => void;
  t: (key: string) => string;
  dir: "ltr" | "rtl";
}

const translations = {
  en: {
    // Navigation
    home: "Home",
    products: "Products",
    about: "About Us",
    contact: "Contact",
    cart: "Cart",
    login: "Login",
    register: "Register",
    logout: "Logout",

    // Common
    addToCart: "Add to Cart",
    buyNow: "Buy Now",
    learnMore: "Learn More",
    viewDetails: "View Details",
    viewAll: "View All",
    search: "Search",
    filter: "Filter",
    sort: "Sort By",
    price: "Price",
    quantity: "Quantity",
    total: "Total",
    subtotal: "Subtotal",
    checkout: "Checkout",
    continueShopping: "Continue Shopping",

    // Homepage
    heroTitle: "Premium Olive Oil from Our Farms",
    heroSubtitle: "Experience the authentic taste of nature's finest olives",
    shopNow: "Shop Now",
    exploreProducts: "Explore Products",
    naturalOrganic: "100% Natural & Organic",
    whyChooseUs: "Why Choose AL EMAD GROUP",
    premium: "Premium Quality",
    organicFeature: "100% Organic",
    traditional: "Traditional Methods",
    discoverApart: "Discover the excellence that sets AL EMAD GROUP apart",
    premiumDesc: "Handpicked from the finest groves of Our Farms",
    organicDesc: "Certified organic farming without chemicals",
    traditionalDesc: "Cold-pressed using centuries-old techniques",
    featuredProducts: "Featured Products",
    popularSelections: "Our most popular selections",
    establishedForOlives: "Established For Olives",
    heritageDesc: "AL EMAD GROUP represents a legacy of excellence in olive oil production. From Our Farms to your table, every drop embodies tradition, purity, and the timeless art of olive cultivation.",
    ourStory: "Our Story",
    getInTouch: "Get In Touch",
    fromOurGroves: "From Our Farms",
    grovesDesc: "Each bottle tells a story of tradition, care, and the perfect harmony between nature and craftsmanship. Experience olive oil as it was meant to be.",
    exploreCollection: "Explore Collection",
    prod1Name: "Extra Virgin Olive Oil",
    prod2Name: "Premium Organic Blend",
    prod3Name: "Our Farms Collection",
    prod4Name: "Heritage Reserve",

    // Products
    allProducts: "All Products",
    extraVirgin: "Extra Virgin",
    organic: "Organic",
    infused: "Infused Oils",
    inStock: "In Stock",
    outOfStock: "Out of Stock",

    // Footer
    followUs: "Follow Us",
    newsletter: "Subscribe to Newsletter",
    emailPlaceholder: "Enter your email",
    subscribe: "Subscribe",
    copyrights: "© 2026 AL EMAD GROUP. All rights reserved.",
    footerQuickLinks: "Quick Links",
    footerContactUs: "Contact Us",
    footerNewsletterDesc: "Get updates on new products and exclusive offers",

    // Admin
    dashboard: "Dashboard",
    orders: "Orders",
    customers: "Customers",
    analytics: "Analytics",
    inventory: "Inventory",
    coupons: "Coupons",

    // About Page
    aboutTitle: "Our Story",
    aboutSubtitle: "AL EMAD GROUP has been crafting premium olive oil from Our Farms, where tradition meets excellence.",
    aboutBadge: "Cultivating Excellence Since 2002",
    aboutSecTitle: "Rooted in Tradition",
    aboutSecDesc1: "Our journey began in 2002 when our founder planted the first olive trees on the sun-drenched hills of Our Farms. What started as a family tradition has grown into a commitment to producing the world's finest olive oil.",
    aboutSecDesc2: "Every bottle of AL EMAD GROUP olive oil tells a story of dedication, craftsmanship, and respect for nature. We harvest our olives at the perfect moment and cold-press them within hours to preserve their exceptional flavor and nutritional properties.",
    aboutValuesTitle: "Our Values",
    aboutValuesSubtitle: "The principles that guide everything we do",
    aboutVal1Title: "Organic Excellence",
    aboutVal1Desc: "We cultivate our olives using 100% organic farming methods, respecting the land and preserving traditional techniques passed down through generations.",
    aboutVal2Title: "Quality First",
    aboutVal2Desc: "Every bottle represents our commitment to excellence. We carefully select and cold-press only the finest olives at peak ripeness.",
    aboutVal3Title: "Passion & Care",
    aboutVal3Desc: "Our family has been producing olive oil for over a century, and every drop reflects our dedication to this timeless craft.",
    aboutVal4Title: "Sustainable Practices",
    aboutVal4Desc: "We protect our environment for future generations through eco-friendly farming and sustainable production methods.",
    aboutTimelineTitle: "Our Journey",
    aboutT1Year: "2002",
    aboutT1Title: "The Beginning",
    aboutT1Desc: "Our family established the first olive grove in Our Farms",
    aboutT2Year: "1975",
    aboutT2Title: "Organic Certification",
    aboutT2Desc: "Became one of the first certified organic olive oil producers in the region",
    aboutT3Year: "2005",
    aboutT3Title: "International Recognition",
    aboutT3Desc: "Won our first international award for extra virgin olive oil excellence",
    aboutT4Year: "2020",
    aboutT4Title: "AL EMAD GROUP",
    aboutT4Desc: "Launched our premium brand to share Our Farms' excellence worldwide",
    aboutTeamTitle: "A Family Tradition",
    aboutTeamDesc: "Four generations of expertise and passion go into every bottle. Our family's commitment to excellence and tradition ensures that you experience olive oil at its absolute finest.",

    // Contact Page
    contactSubtitle: "Have questions? We'd love to hear from you. Send us a message and we'll respond as soon as possible.",
    contactFormTitle: "Send us a message",
    contactYourName: "Your Name",
    contactEmail: "Email Address",
    contactSubject: "Subject",
    contactMessage: "Message",
    contactPlaceholderName: "Enter your full name",
    contactPlaceholderEmail: "Enter your email address",
    contactPlaceholderSubject: "How can we help?",
    contactPlaceholderMessage: "Tell us more about your inquiry...",
    contactSendMessage: "Send Message",
    contactInfo1Title: "Visit Us",
    contactInfo1Desc: "Our Farms, Olive Grove District",
    contactInfo1Sub: "12345 Our Farms Way",
    contactInfo2Title: "Call Us",
    contactInfo2Desc: "01062687174",
    contactInfo2Sub: "Mon-Fri, 9:00 AM - 6:00 PM",
    contactInfo3Title: "Email Us",
    contactInfo3Desc: "aalemadgroup@gmail.com",
    contactInfo4Title: "Working Hours",
    contactInfo4Desc: "Monday - Friday: 9:00 AM - 6:00 PM",
    contactInfo4Sub: "Saturday: 10:00 AM - 4:00 PM",
    contactMapView: "Map View",
    contactMapLoc: "Our Farms Location",
    contactToastSuccess: "Thank you for your message! We'll get back to you soon.",

    // Cart Page
    cartEmpty: "Your cart is empty",
    cartEmptyDesc: "Discover our premium olive oil collection",
    cartSummary: "Order Summary",
    cartShipping: "Shipping",
    cartTax: "Tax (10%)",
    cartFreeReturns: "Free returns within 30 days",
    cartSecurePay: "Secure payment processing",
    cartShipsSoon: "Ships within 2-3 business days",

    // Products Page
    prodSubtitle: "Discover our premium selection of olive oils from Our Farms",
    prodFilters: "Filters",
    prodSortFeatured: "Featured",
    prodSortPriceLow: "Price: Low to High",
    prodSortPriceHigh: "Price: High to Low",
    prodSortName: "Name: A-Z",
    prodSortNewest: "Newest First",
    prodPriceRange: "Price Range",
    prodShowing: "Showing",
    prodOf: "of",
    prodProducts: "products",
    prodNoneFound: "No products found",
    prodClearFilters: "Clear Filters",

    // Product Details
    prodBackToProducts: "Back to Products",
    prodCertifiedOrganic: "Certified Organic",
    prodReviews: "reviews",
    prodSelectSize: "Select Size",
    prodBenefits1: "Free shipping on orders over EGP 2,500",
    prodBenefits2: "100% satisfaction guarantee",
    prodBenefits3: "30-day easy returns",
    prodFeaturesTitle: "Product Features",
    prodTabDesc: "Description",
    prodTabNutr: "Nutritional Info",
    prodTabReviews: "Reviews",
    prodNutrTitle: "Nutritional Information",
    prodNutr1: "Calories",
    prodNutr1Val: "120 per tbsp",
    prodNutr2: "Total Fat",
    prodNutr2Val: "14g",
    prodNutr3: "Saturated Fat",
    prodNutr3Val: "2g",
    prodNutr4: "Vitamin E",
    prodNutr4Val: "15% DV",
    prodNutr5: "Polyphenols",
    prodNutr5Val: "High",
    prodNutrNote: "* Percent Daily Values are based on a 2,000 calorie diet",
    prodDescParagraph1: "Our premium Extra Virgin Olive Oil is cold-pressed from carefully selected olives harvested at peak ripeness. With its rich, fruity flavor and golden-green hue, this exceptional oil embodies the essence of Our Farms' tradition.",
    prodDescParagraph2: "Each bottle represents generations of expertise in olive cultivation and oil production. The result is a golden-green elixir with a fruity aroma, peppery finish, and rich, complex flavor profile that elevates any dish.",
    prodDescParagraph3: "Perfect for drizzling over salads, finishing pasta dishes, or dipping with fresh bread. This versatile oil also excels in cooking, maintaining its beneficial properties even at higher temperatures.",
    prodFeature1: "100% Cold-pressed extra virgin",
    prodFeature2: "First harvest premium olives",
    prodFeature3: "Rich in antioxidants",
    prodFeature4: "Perfect for cooking & dressing",
    prodFeature5: "Glass bottle packaging",
    prodFeature6: "Certified organic",
    prodCustReviews: "Customer Reviews",
    prodBasedOn: "Based on 128 reviews",
    prodReview1Name: "Sarah M.",
    prodReview1Comment: "Absolutely exceptional! The flavor is rich and authentic. Best olive oil I've ever used.",
    prodReview2Name: "Michael R.",
    prodReview2Comment: "Premium quality at its finest. The peppery finish is perfect. Highly recommend!",
    prodReview3Name: "Emma L.",
    prodReview3Comment: "This olive oil has transformed my cooking. So fresh and flavorful!",
    prodToastAdded: "Added",
    prodToastToCart: "to cart",

    // Login Page
    loginWelcome: "Welcome Back",
    loginSubtitle: "Sign in to your AL EMAD GROUP account",
    loginEmail: "Email Address",
    loginPassword: "Password",
    loginPlaceholderEmail: "Enter your email address",
    loginPlaceholderPassword: "Enter your password",
    loginRemember: "Remember me",
    loginForgot: "Forgot password?",
    loginDontHave: "Don't have an account?",
    loginCreateOne: "Create one",

    // Forgot Password Page
    forgotTitle: "Forgot Password",
    forgotSubtitle: "Enter your email to receive verification code",
    forgotBtn: "Send OTP Code",
    forgotBackToLogin: "Back to Login",
    forgotSuccessTitle: "Password Updated",
    forgotSuccessDesc: "Your password has been successfully updated. You can now log in with your new password.",
    forgotOtpTitle: "Enter Verification Code",
    forgotOtpSubtitle: "We've sent a 6-digit verification code to your email. Enter it below to proceed.",
    forgotOtpPlaceholder: "Enter 6-digit code",
    forgotOtpVerifyBtn: "Verify Code",
    forgotOtpResend: "Didn't receive the code? Resend",
    forgotOtpResending: "Resending...",
    forgotOtpSentToast: "Verification code sent successfully!",
    forgotOtpInvalidToast: "Invalid verification code. Please try again.",
    forgotNewPassTitle: "Create New Password",
    forgotNewPassSubtitle: "Please set a strong, new password for your account",
    forgotNewPassPlaceholder: "Enter new password",
    forgotConfirmPassPlaceholder: "Confirm new password",
    forgotResetBtn: "Update Password",
    forgotSuccessToast: "Password updated successfully!",



    // Register Page
    registerTitle: "Create Account",
    registerSubtitle: "Join AL EMAD GROUP family today",
    registerFullName: "Full Name",
    registerPlaceholderName: "Enter your full name",
    registerPlaceholderPassword: "Create a password",
    registerConfirmPassword: "Confirm Password",
    registerPlaceholderConfirm: "Confirm your password",
    registerAgree: "I agree to the",
    registerTerms: "Terms of Service",
    registerAnd: "and",
    registerPrivacy: "Privacy Policy",
    registerAlready: "Already have an account?",
    registerSignIn: "Sign in",
    registerPasswordMismatch: "Passwords don't match!",

    // Checkout Page
    checkoutBack: "Back to Cart",
    checkoutStepShipping: "Shipping",
    checkoutStepPayment: "Payment",
    checkoutStepReview: "Review",
    checkoutShipTitle: "Shipping Information",
    checkoutFirstName: "First Name",
    checkoutLastName: "Last Name",
    checkoutEmail: "Email",
    checkoutPhone: "Phone",
    checkoutAddress: "Address",
    checkoutCity: "City",
    checkoutState: "State",
    checkoutZip: "ZIP Code",
    checkoutCountry: "Country",
    checkoutRequired: "*",
    checkoutShipMethod: "Shipping Method",
    checkoutStandardShip: "Standard Shipping",
    checkoutStandardDays: "5-7 business days",
    checkoutExpressShip: "Express Shipping",
    checkoutExpressDays: "2-3 business days",
    checkoutPayTitle: "Payment Information",
    checkoutCardNumber: "Card Number",
    checkoutCardHolder: "Cardholder Name",
    checkoutExpiry: "Expiry Date",
    checkoutCvv: "CVV",
    checkoutEncrypted: "Your payment information is encrypted and secure",
    checkoutPlaceOrder: "Place Order",
    checkoutProcessing: "Processing...",
    checkoutReviewTitle: "Review Your Order",
    checkoutReviewSub: "Review details before placing the order",
    checkoutShipAddress: "Shipping Address",
    checkoutOrderItems: "Order Items",
    checkoutBackBtn: "Back",
    checkoutPayBtn: "Continue to Payment",
    checkoutReviewBtn: "Review Order",
    checkoutSecureCheck: "Secure checkout",
    checkoutMoneyBack: "Money-back guarantee",
    checkoutEmptyDesc: "Add some products to checkout",
    checkoutBrowse: "Browse Products",
    checkoutSuccess: "Order placed successfully!",
    checkoutRequiredFields: "Please fill in all required fields",
  },
  ar: {
    // Navigation
    home: "الرئيسية",
    products: "المنتجات",
    about: "من نحن",
    contact: "تواصل معنا",
    cart: "السلة",
    login: "تسجيل دخول",
    register: "إنشاء حساب",
    logout: "تسجيل خروج",

    // Common
    addToCart: "أضف للسلة",
    buyNow: "اشتري الآن",
    learnMore: "اعرف المزيد",
    viewDetails: "عرض التفاصيل",
    viewAll: "عرض الكل",
    search: "بحث",
    filter: "تصفية",
    sort: "ترتيب حسب",
    price: "السعر",
    quantity: "الكمية",
    total: "الإجمالي",
    subtotal: "المجموع الفرعي",
    checkout: "إتمام الشراء",
    continueShopping: "متابعة التسوق",

    // Homepage
    heroTitle: "زيت زيتون فاخر من مزارعنا",
    heroSubtitle: "اختبر الطعم الأصيل لأجود أنواع الزيتون الطبيعي",
    shopNow: "تسوق الآن",
    exploreProducts: "استكشف المنتجات",
    naturalOrganic: "طبيعي وعضوي 100%",
    whyChooseUs: "لماذا تختار مجموعة العماد",
    premium: "جودة فاخرة",
    organicFeature: "عضوي 100%",
    traditional: "طرق تقليدية",
    discoverApart: "اكتشف التميز الذي يميز مجموعة العماد",
    premiumDesc: "منتقاة بعناية من أفضل مزارعنا",
    organicDesc: "زراعة عضوية معتمدة بدون استخدام مواد كيميائية",
    traditionalDesc: "عصر بارد باستخدام تقنيات متوارثة منذ قرون",
    featuredProducts: "المنتجات المميزة",
    popularSelections: "خيارنا الأكثر شعبية ورواجاً",
    establishedForOlives: "تأسست من أجل الزيتون",
    heritageDesc: "تمثل مجموعة العماد إرثاً من التميز في إنتاج زيت الزيتون. من مزارعنا إلى طاولتك، تجسد كل قطرة التقاليد والنقاء وفن زراعة الزيتون الخالد.",
    ourStory: "قصتنا",
    getInTouch: "تواصل معنا",
    fromOurGroves: "من مزارعنا",
    grovesDesc: "تحكي كل زجاجة قصة من التقاليد والعناية والانسجام التام بين الطبيعة والحرفية. جرب زيت الزيتون كما يجب أن يكون.",
    exploreCollection: "استكشف المجموعة",
    prod1Name: "زيت زيتون بكر ممتاز",
    prod2Name: "مزيج عضوي فاخر",
    prod3Name: "مجموعة مزارعنا",
    prod4Name: "احتياطي الإرث",

    // Products
    allProducts: "جميع المنتجات",
    extraVirgin: "بكر ممتاز",
    organic: "عضوي",
    infused: "زيوت منكهة",
    inStock: "متوفر",
    outOfStock: "غير متوفر",

    // Footer
    followUs: "تابعنا",
    newsletter: "اشترك في النشرة البريدية",
    emailPlaceholder: "أدخل بريدك الإلكتروني",
    subscribe: "اشتراك",
    copyrights: "© 2026 مجموعة العماد. جميع الحقوق محفوظة.",
    footerQuickLinks: "روابط سريعة",
    footerContactUs: "اتصل بنا",
    footerNewsletterDesc: "احصل على آخر التحديثات للمنتجات الجديدة والعروض الحصرية",

    // Admin
    dashboard: "لوحة التحكم",
    orders: "الطلبات",
    customers: "العملاء",
    analytics: "التحليلات",
    inventory: "المخزون",
    coupons: "الكوبونات",

    // About Page
    aboutTitle: "قصتنا",
    aboutSubtitle: "دأبت مجموعة العماد على إنتاج زيت زيتون بكر ممتاز من مزارعنا، حيث تلتقي الأصالة بالتميز.",
    aboutBadge: "نزرع التميز منذ عام 2002",
    aboutSecTitle: "متجذر في التقاليد",
    aboutSecDesc1: "بدأت رحلتنا في عام 2002 عندما زرع مؤسسنا أشجار الزيتون الأولى على تلال مزارعنا المشمسة. ما بدأ كتقليد عائلي نما ليصبح التزاماً بإنتاج أجود أنواع زيت الزيتون في العالم.",
    aboutSecDesc2: "تحكي كل زجاجة من زيت زيتون مجموعة العماد قصة من التفاني والحرفية واحترام الطبيعة. نحصد زيتوننا في اللحظة المثالية ونعصره على البارد في غضون ساعات للحفاظ على نكهته الاستثنائية وفوائده الغذائية.",
    aboutValuesTitle: "قيمنا",
    aboutValuesSubtitle: "المبادئ التي توجه كل ما نقوم به",
    aboutVal1Title: "التميز العضوي",
    aboutVal1Desc: "نحن نزرع زيتوننا باستخدام طرق زراعة عضوية 100%، مع احترام الأرض والحفاظ على التقنيات التقليدية المتوارثة عبر الأجيال.",
    aboutVal2Title: "الجودة أولاً",
    aboutVal2Desc: "كل زجاجة تمثل التزامنا بالتميز. نختار بعناية ونعصر على البارد أجود أنواع الزيتون في قمة نضجه.",
    aboutVal3Title: "الشغف والعناية",
    aboutVal3Desc: "تنتج عائلتنا زيت الزيتون منذ أكثر من قرن، وتجسد كل قطرة تفانينا في هذه الحرفة الخالدة.",
    aboutVal4Title: "ممارسات مستدامة",
    aboutVal4Desc: "نحن نحمي بيئتنا للأجيال القادمة من خلال الزراعة الصديقة للبيئة وطرق الإنتاج المستدامة.",
    aboutTimelineTitle: "مسيرتنا",
    aboutT1Year: "2002",
    aboutT1Title: "البداية",
    aboutT1Desc: "أنشأت عائلتنا أول بستان زيتون في مزارعنا",
    aboutT2Year: "1975",
    aboutT2Title: "شهادة المنتجات العضوية",
    aboutT2Desc: "أصبحنا من أوائل منتجي زيت الزيتون العضوي المعتمدين في المنطقة",
    aboutT3Year: "2005",
    aboutT3Title: "اعتراف دولي",
    aboutT3Desc: "فزنا بأول جائزة دولية للتميز في زيت الزيتون البكر الممتاز",
    aboutT4Year: "2020",
    aboutT4Title: "مجموعة العماد",
    aboutT4Desc: "أطلقنا علامتنا التجارية الفاخرة لمشاركة تميز مزارعنا في جميع أنحاء العالم",
    aboutTeamTitle: "تقليد عائلي",
    aboutTeamDesc: "أربعة أجيال من الخبرة والشغف توضع في كل زجاجة. يضمن التزام عائلتنا بالتميز والتقاليد أن تجد زيت الزيتون في أفضل حالاته على الإطلاق.",

    // Contact Page
    contactSubtitle: "هل لديك أي استفسار؟ يسعدنا دائماً تواصلكم معنا. أرسل لنا رسالة وسنقوم بالرد عليك في أقرب وقت ممكن.",
    contactFormTitle: "أرسل لنا رسالة",
    contactYourName: "الاسم الكامل",
    contactEmail: "البريد الإلكتروني",
    contactSubject: "الموضوع",
    contactMessage: "الرسالة",
    contactPlaceholderName: "أدخل اسمك الكامل",
    contactPlaceholderEmail: "أدخل بريدك الإلكتروني",
    contactPlaceholderSubject: "كيف يمكننا مساعدتك؟",
    contactPlaceholderMessage: "أخبرنا المزيد عن استفسارك...",
    contactSendMessage: "إرسال الرسالة",
    contactInfo1Title: "تفضل بزيارتنا",
    contactInfo1Desc: "مزارعنا، حي بساتين الزيتون",
    contactInfo1Sub: "12345 طريق مزارعنا",
    contactInfo2Title: "اتصل بنا",
    contactInfo2Desc: "01062687174",
    contactInfo2Sub: "الإثنين - الجمعة، 9:00 صباحاً - 6:00 مساءً",
    contactInfo3Title: "بريدنا الإلكتروني",
    contactInfo3Desc: "aalemadgroup@gmail.com",
    contactInfo4Title: "ساعات العمل",
    contactInfo4Desc: "الإثنين - الجمعة: 9:00 صباحاً - 6:00 مساءً",
    contactInfo4Sub: "السبت: 10:00 صباحاً - 4:00 مساءً",
    contactMapView: "عرض الخريطة",
    contactMapLoc: "موقع مزارعنا",
    contactToastSuccess: "نشكرك على رسالتك! سنتصل بك قريباً.",

    // Cart Page
    cartEmpty: "سلة التسوق فارغة",
    cartEmptyDesc: "اكتشف مجموعتنا المميزة والفاخرة من زيت الزيتون",
    cartSummary: "ملخص الطلب",
    cartShipping: "الشحن",
    cartTax: "الضريبة (10%)",
    cartFreeReturns: "إرجاع مجاني خلال 30 يوماً",
    cartSecurePay: "معالجة دفع آمنة وموثوقة",
    cartShipsSoon: "يتم الشحن خلال 2-3 أيام عمل",

    // Products Page
    prodSubtitle: "اكتشف تشكيلتنا الفاخرة من زيوت مزارعنا",
    prodFilters: "تصفية",
    prodSortFeatured: "المميز",
    prodSortPriceLow: "السعر: من الأقل للأعلى",
    prodSortPriceHigh: "السعر: من الأعلى للأقل",
    prodSortName: "الاسم: أ-ي",
    prodSortNewest: "الأحدث أولاً",
    prodPriceRange: "نطاق السعر",
    prodShowing: "عرض",
    prodOf: "من",
    prodProducts: "منتجات",
    prodNoneFound: "لم يتم العثور على منتجات",
    prodClearFilters: "مسح التصفية",

    // Product Details
    prodBackToProducts: "العودة للمنتجات",
    prodCertifiedOrganic: "عضوي معتمد",
    prodReviews: "تقييمات",
    prodSelectSize: "اختر الحجم",
    prodBenefits1: "شحن مجاني للطلبات فوق 2,500 ج.م",
    prodBenefits2: "ضمان رضا 100%",
    prodBenefits3: "إرجاع سهل ومرن خلال 30 يوماً",
    prodFeaturesTitle: "ميزات المنتج",
    prodTabDesc: "الوصف",
    prodTabNutr: "القيمة الغذائية",
    prodTabReviews: "التقييمات",
    prodNutrTitle: "المعلومات الغذائية",
    prodNutr1: "السعرات الحرارية",
    prodNutr1Val: "120 لكل ملعقة كبيرة",
    prodNutr2: "الدهون الكلية",
    prodNutr2Val: "14 جرام",
    prodNutr3: "الدهون المشبعة",
    prodNutr3Val: "2 جرام",
    prodNutr4: "فيتامين E",
    prodNutr4Val: "15% من القيمة اليومية",
    prodNutr5: "البوليفينول",
    prodNutr5Val: "مرتفع",
    prodNutrNote: "* تعتمد النسب المئوية للقيم اليومية على نظام غذائي يحتوي على 2000 سعرة حرارية",
    prodDescParagraph1: "يُعصر زيت الزيتون البكر الممتاز على البارد من حبات زيتون منتقاة بعناية في قمة نضجها. بنكهته الفاكهية الغنية ولونه الأخضر الذهبي، يجسد هذا الزيت الفريد جوهر تقاليد مزارعنا.",
    prodDescParagraph2: "تمثل كل زجاجة أجيالاً من الخبرة في زراعة الزيتون وإنتاج الزيت. والنتيجة هي إكسير ذهبي مخضر برائحة فاكهية، ولمسة حارة، ونكهة غنية ومعقدة ترتقي بأي طبق.",
    prodDescParagraph3: "مثالي للسكب فوق السلطات، وإضافته في نهاية أطباق المعكرونة، أو غميس مع الخبز الطازج. كما أنه رائع للطهي، حيث يحافظ على خصائصه المفيدة حتى في درجات الحرارة المرتفعة.",
    prodFeature1: "زيت بكر ممتاز معصور على البارد 100%",
    prodFeature2: "زيتون من أول قطاف ممتاز",
    prodFeature3: "غني بمضادات الأكسدة",
    prodFeature4: "مثالي للطهي وتتبيل السلطات",
    prodFeature5: "تعبئة في زجاجات فاخرة",
    prodFeature6: "عضوي موثق ومعتمد",
    prodCustReviews: "تقييمات العملاء",
    prodBasedOn: "بناءً على 128 تقييم",
    prodReview1Name: "سارة م.",
    prodReview1Comment: "استثنائي ولذيذ للغاية! النكهة غنية وأصلية. أفضل زيت زيتون استخدمته على الإطلاق.",
    prodReview2Name: "مايكل ر.",
    prodReview2Comment: "جودة ممتازة في أرقى صورها. النكهة الحارة في النهاية مثالية. أنصح به بشدة!",
    prodReview3Name: "إيما ل.",
    prodReview3Comment: "لقد غيّر هذا الزيت من جودة طبخي. طازج ولذيذ جداً!",
    prodToastAdded: "تم إضافة",
    prodToastToCart: "إلى السلة",

    // Login Page
    loginWelcome: "مرحباً بك مجدداً",
    loginSubtitle: "قم بتسجيل الدخول إلى حساب مجموعة العماد الخاص بك",
    loginEmail: "البريد الإلكتروني",
    loginPassword: "كلمة المرور",
    loginPlaceholderEmail: "أدخل بريدك الإلكتروني",
    loginPlaceholderPassword: "أدخل كلمة المرور الخاصة بك",
    loginRemember: "تذكرني",
    loginForgot: "نسيت كلمة المرور؟",
    loginDontHave: "ليس لديك حساب؟",
    loginCreateOne: "أنشئ حساباً جديداً",

    // Forgot Password Page
    forgotTitle: "نسيت كلمة المرور",
    forgotSubtitle: "أدخل بريدك الإلكتروني لتلقي رمز التحقق",
    forgotBtn: "إرسال رمز التحقق",
    forgotBackToLogin: "العودة إلى تسجيل الدخول",
    forgotSuccessTitle: "تم تحديث كلمة المرور",
    forgotSuccessDesc: "تم تحديث كلمة المرور الخاصة بك بنجاح. يمكنك الآن تسجيل الدخول باستخدام كلمة المرور الجديدة.",
    forgotOtpTitle: "أدخل رمز التحقق",
    forgotOtpSubtitle: "لقد أرسلنا رمز تحقق مكون من 6 أرقام إلى بريدك الإلكتروني. أدخله أدناه للمتابعة.",
    forgotOtpPlaceholder: "أدخل الرمز المكون من 6 أرقام",
    forgotOtpVerifyBtn: "تحقق من الرمز",
    forgotOtpResend: "لم تصلك رسالة؟ إعادة إرسال الرمز",
    forgotOtpResending: "جاري إعادة الإرسال...",
    forgotOtpSentToast: "تم إرسال رمز التحقق بنجاح!",
    forgotOtpInvalidToast: "رمز التحقق غير صحيح! يرجى المحاولة مرة أخرى.",
    forgotNewPassTitle: "إنشاء كلمة مرور جديدة",
    forgotNewPassSubtitle: "يرجى تعيين كلمة مرور جديدة وقوية لحسابك",
    forgotNewPassPlaceholder: "أدخل كلمة المرور الجديدة",
    forgotConfirmPassPlaceholder: "تأكيد كلمة المرور الجديدة",
    forgotResetBtn: "تحديث كلمة المرور",
    forgotSuccessToast: "تم تحديث كلمة المرور بنجاح!",



    // Register Page
    registerTitle: "إنشاء حساب",
    registerSubtitle: "انضم إلى عائلة مجموعة العماد اليوم",
    registerFullName: "الاسم الكامل",
    registerPlaceholderName: "أدخل اسمك الكامل",
    registerPlaceholderPassword: "أنشئ كلمة مرور قوية",
    registerConfirmPassword: "تأكيد كلمة المرور",
    registerPlaceholderConfirm: "أعد كتابة كلمة المرور",
    registerAgree: "أنا أوافق على",
    registerTerms: "شروط الخدمة",
    registerAnd: "و",
    registerPrivacy: "سياسة الخصوصية",
    registerAlready: "هل لديك حساب بالفعل؟",
    registerSignIn: "تسجيل الدخول",
    registerPasswordMismatch: "كلمتا المرور غير متطابقتين!",

    // Checkout Page
    checkoutBack: "العودة إلى السلة",
    checkoutStepShipping: "الشحن",
    checkoutStepPayment: "الدفع",
    checkoutStepReview: "المراجعة",
    checkoutShipTitle: "معلومات الشحن",
    checkoutFirstName: "الاسم الأول",
    checkoutLastName: "اسم العائلة",
    checkoutEmail: "البريد الإلكتروني",
    checkoutPhone: "رقم الهاتف",
    checkoutAddress: "العنوان",
    checkoutCity: "المدينة",
    checkoutState: "الولاية / المنطقة",
    checkoutZip: "الرمز البريدي",
    checkoutCountry: "البلد",
    checkoutRequired: "*",
    checkoutShipMethod: "طريقة الشحن",
    checkoutStandardShip: "شحن عادي",
    checkoutStandardDays: "5-7 أيام عمل",
    checkoutExpressShip: "شحن سريع",
    checkoutExpressDays: "2-3 أيام عمل",
    checkoutPayTitle: "معلومات الدفع",
    checkoutCardNumber: "رقم البطاقة",
    checkoutCardHolder: "اسم حامل البطاقة",
    checkoutExpiry: "تاريخ الانتهاء",
    checkoutCvv: "رمز التحقق (CVV)",
    checkoutEncrypted: "معلومات الدفع الخاصة بك مشفرة وآمنة تماماً",
    checkoutPlaceOrder: "تأكيد الطلب",
    checkoutProcessing: "جاري معالجة الطلب...",
    checkoutReviewTitle: "مراجعة الطلب",
    checkoutReviewSub: "يرجى مراجعة تفاصيل طلبك قبل التأكيد",
    checkoutShipAddress: "عنوان الشحن",
    checkoutOrderItems: "المنتجات المطلوبة",
    checkoutBackBtn: "رجوع",
    checkoutPayBtn: "الذهاب إلى الدفع",
    checkoutReviewBtn: "مراجعة الطلب",
    checkoutSecureCheck: "إتمام دفع آمن",
    checkoutMoneyBack: "ضمان استعادة الأموال",
    checkoutEmptyDesc: "أضف بعض المنتجات لإتمام عملية الشراء",
    checkoutBrowse: "استعرض المنتجات",
    checkoutSuccess: "تم تسجيل طلبك بنجاح!",
    checkoutRequiredFields: "يرجى تعبئة الحقول المطلوبة",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("en");

  useEffect(() => {
    const savedLang = localStorage.getItem("language") as Language;
    if (savedLang) {
      setLanguage(savedLang);
    }
  }, []);

  useEffect(() => {
    document.documentElement.lang = language;
    document.documentElement.dir = language === "ar" ? "rtl" : "ltr";
  }, [language]);

  const toggleLanguage = () => {
    const newLang = language === "en" ? "ar" : "en";
    setLanguage(newLang);
    localStorage.setItem("language", newLang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.en] || key;
  };

  return (
    <LanguageContext.Provider
      value={{
        language,
        toggleLanguage,
        t,
        dir: language === "ar" ? "rtl" : "ltr",
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
}
